version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "microservicescrud"
    ports:
      - "3306:3306"
    networks:
       mysql-compose-network:
         ipv4_address: 10.5.0.5
  
  apimicroservices:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: lucianoromero/apimicroservicescrud
        environment:
               - DB_URL=jdbc:mysql://10.5.0.5:3306/microservicescrud?createDatabaseIfNotExist=true&serverTimezone=UTC
               - DB_USER=root
               - DB_SENHA=123456
        ports:
            - "8080:8080"  
        networks: 
             mysql-compose-network:
              ipv4_address: 10.5.0.7
        depends_on:
            - "mysqlsrv"

networks: 
  mysql-compose-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
