version: '3'
services:
  mysql:
    image: mysql/mysql-server
    container_name: DBbancoCompose
    ports:
      - "33060:33060"
    networks:
      redeteste-network:
       ipv4_address: 10.5.0.5
  
  apimicroservicescrud:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: lucianoromero/apimicroservicescrud
        container_name: apimicroservicescrud
        environment:
            DB_URL: 'mysql://10.5.0.5:3306/microservicescrud?createDatabaseIfNotExist=true&serverTimezone=UTC'
            DB_USER: 'root'
            DB_SENHA: '123456'
        ports:
            - "8080:8080"  
        networks: 
            - redeteste-network
        depends_on:
            - "mysql"

networks:
  redeteste-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
